### ISSUE TITLE
Unable to Install a debugger

### ISSUE THREAD

**Issue by FotiadisM** [Pocco81/DAPInstall.nvim#14] opened 2021-08-13 14:18 UTC
Hello, it seems that I am unable to install any debugger using `DIInstall <debugger>`, it prints a message and then kills Neovim

![cropped](https://user-images.githubusercontent.com/47476275/129370695-8a66f82d-9a8d-4c1e-9a7a-a09f0020981e.png)

My config:
```lua
use {
	"Pocco81/DAPInstall.nvim",
	config = function()
		local dap_install = require("dap-install")
                -- default values
		dap_install.setup({
			installation_path = vim.fn.stdpath("data") .. "/dapinstall/",
			verbosely_call_debuggers = false,
		})
		dap_install.config("go_delve_dbg", {})
	end
}
```
OS: Ubuntu 20.04
Neovim: 0.5.0+ubuntu2+git202108111755-7d2233fad-d569569c9-9cb9a8f8c~ubuntu20.04.1 (I use the unstable ppa)

**Comment by Pocco81** [comment] 2021-08-13 17:31
hmmm that's weird I was able to install the one just now:

![image](https://user-images.githubusercontent.com/58336662/129397420-8a26b348-150f-4341-b463-d03cbcd2edfc.png)

**Comment by Pocco81** [comment] 2021-08-13 17:56
It's probably the unstable PPA for Ubuntu. Could you try the stable 0.5?

**Comment by FotiadisM** [comment] 2021-08-14 07:08
0.5 is not yet available, so I tried the 0.5 nvim.appimage and I had the same exact problem.

Is there any place where I can look for logs and paste them here?

**Comment by Pocco81** [comment] 2021-08-17 04:52
> Is there any place where I can look for logs and paste them here?

DAPInstall doesn't do any logging so from that part I don't think you'll find much. But again, this issue doesn't seem related to this project (as shown by the error message). What failed was the ui compositor, and I'm not sure if nvim devs added logging for that.

However, we can't discard the fact that it might be an issue with the app image either.

**Comment by FotiadisM** [comment] 2021-08-18 09:50
I just tried it on Fedora 34 with the stable Neovim 0.5 dnf package and still run to the same problem. So it's not the app image for sure.

In all the tests, I used the gnome-terminal (3.36.2 in ubuntu and 3.40.2 in Fedora), when I find the time I will try running with another terminal.

**Comment by Pocco81** [comment] 2021-08-18 15:35
This is very weird... I'm on Arch Linux using [the package](https://archlinux.org/packages/community/x86_64/neovim/) from the official repo and I do can install debuggers:

![image](https://user-images.githubusercontent.com/58336662/129927703-0d10ea25-ae81-46b7-b82c-0ce895f77f3d.png)

Perhaps the problem might be caused by your nvim conf?

**Comment by Pocco81** [comment] 2021-08-22 02:58
Closing because OP is gone.

**Closed by Pocco81** 2021-08-22 02:58 UTC
Labels: OP is gone
